version: '3.7'

services:
  # REST API running on Node JS container
  app:
    container_name: lafs-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    # Link this container to the Mongo DB container
    links:
      - mongo
    # Pass in environment variables for database host and name
    environment:
      - DB_HOST=mongo
      - DB_NAME=lafs-db
    # Attach the external network to this container
    networks:
      - lafs-net

  # MongoDB storage container
  mongo:
    container_name: lafs-db
    image: 'mongo:4'
    ports:
      - '27017:27017'
    # Attach the external network to this container
    networks:
      - lafs-net
    # Persist MongoDB data
    volumes:
      - mongo-data:/data/db

# Define external network
networks:
  lafs-net:
    external: true

# Define volumes
volumes:
  mongo-data:
